### ISSUE TITLE
404 on put contacts/:id

### ISSUE THREAD

**Issue by opsb** [cerebris/peeps-ember-orbit#1]
I know this is very much in the draft phase but I thought it might be useful to document issues that I found while trying this out with peeps-uuid.

Currently when a new contact is created orbit.js does a PUT to /contacts/:id but the server responds with a 404. According to http://jsonapi.org/format/#crud-creating-client-ids it looks like the request should be a POST (even though it includes a uuid). I'm not entirely sure though because http://jsonapi.org/format/#crud-creating-client-ids doesn't mention whether PUT or POST should be used.

**Comment by dgeb** [comment]
Yes, JSON API requires a POST to create, even when using client-generated IDs.

We'll be pushing a new revision of JSON API very soon and then I'll ensure that Orbit's JSONAPISource is fully compliant.

**Comment by opsb** [comment]
Ok, I'll hold off on looking at anything to do with JSONAPISource for now then.

**Comment by dgeb** [comment]
Resolved.
